version: '3.1'

services:
  generator:
    
    image:  my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-14}
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8061:8025"
  