version: '3.1'

services:
  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - teamcity-server-datadir:/data/teamcity_server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    privileged: true
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL: http://teamcity:8111
      - DOCKER_IN_DOCKER: start
    volumes:
      - /var/run/cocker.sock:/var/run/docker.sock
volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
    